name: Notify Cowneck of Update

on:
  push:
    branches: ["main"]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.COWNECK_UPDATE_TOKEN }}
          repository: your-username/cowneck
          event-type: update-game

